---
title: "Análisis de datos de COVID-19 en Costa Rica - ggplot2 y DT"
author: "Emily Diaz"
date: '2022-05-25'
output: 
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Presentación

Este documento presenta varios gráficos estadísticos de los datos de COVID-19 en Costa Rica publicados por el Ministerio de Salud en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/)


## Entradas

```{r cargar_paquetes}
library("ggplot2")
library("dplyr")
library("DT")
library("readr")
library("plotly")
```


```{r carga-datos}
covid <- read.csv(file = "05_24_22_CSV_GENERAL.csv", sep = ";")
```


## Opciones generales

```{r importacion_datos_generales}
covid_nacional <-
  read_delim(
    file = "C:/Users/Universidad/analisis-covid-intermedio/05_24_22_CSV_GENERAL.csv",
    delim = ";",
    col_select = c("FECHA", "positivos", "fallecidos", "RECUPERADOS", "activos")
  )
```

```{r importacion_positivos_canton}
covid_cantonal_positivos <-
  read_delim(
    file = "C:/Users/Universidad/analisis-covid-intermedio/05_24_22_CSV_POSITIVOS.csv",
    delim = ";",
    locale = locale(encoding = "WINDOWS-1252"), # esto es para resolver el problema con las tildes
    col_select = c("canton", "24/05/2022")
  )
```

```{r cambio_nombre}
covid_cantonal_positivos <-
  covid_cantonal_positivos %>%
  rename(positivos = '24/05/2022')
```


```{r cambio_nombres}
covid_nacional <-
  covid_nacional %>%
  select(fecha = FECHA,
         positivos,
         fallecidos,
         recuperados = RECUPERADOS,
         activos) %>%
  mutate(fecha = as.Date(fecha, format = "%d/%m/%Y"))
```


## Salidas



### Casos generales tabla

```{r casos_generales_tabla}
covid_nacional %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```


### Casos generales gráfico lineas

```{r grafico_generales}
ggplot2_covid_nacional_linea <-
  covid_nacional %>%
  ggplot(aes(x = fecha, y = value, color = variable)) +
  ggtitle("Casos acumulados de covid-19 en Costa Rica") +
  xlab("Fecha") +
  ylab("Casos") +
  geom_line(aes(y = positivos, color = "Positivos")) +
  geom_line(aes(y = recuperados, color = "Recuperados")) +
  geom_line(aes(y = activos, color = "Activos")) +
  geom_line(aes(y = fallecidos, color = "Fallecidos")) +
  scale_colour_manual(
    "",
    values = c(
      "Positivos" = "blue",
      "Recuperados" = "green",
      "Activos" = "red",
      "Fallecidos" = "black"
    )
  )

```

```{r muestra_generales}
 ggplotly(ggplot2_covid_nacional_linea) %>% config(locale = 'es')
```


### Casos por cantón tabla

```{r casos_canton}
covid_cantonal_positivos %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))

```


### Casos por cantón gráfico de barras

```{r grafico_canton}
ggplot2_covid_cantonal_barras <- ggplot(data = covid_cantonal_positivos, aes(x = canton, y = positivos)) + 
    geom_bar(stat="identity", position="dodge") +
    ggtitle("Casos positivos por canton de COVID-19 en Costa Rica") +
    xlab("Cantones") +
    ylab("Positivos")
```

```{r muestra-canton}
 ggplotly(ggplot2_covid_cantonal_barras) %>% config(locale = 'es')
```





```{r otro_grafico}
ggplot(data = covid_cantonal_positivos, aes(x = canton, y = positivos)) + 
  geom_bar(stat = "identity", width=0.4)
```

```{r ihdihd}
ggplot2_covid_cantonal_barras <-
  covid_cantonal_positivos %>%
  ggplot(aes(x = canton, y = positivos, color = variable)) +
  ggtitle("Casos acumulados de covid-19 en Costa Rica") +
  xlab("Cantones") +
  ylab("Positivos") 
```



